### ISSUE TITLE
Issue #1 - Mads

### ISSUE THREAD

**Issue by iamyufi** [QMalikat/LearnGit#4]
Mads lugter, han har brug for axe bodyspray.

**Comment by Sk0vsted** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by iamyufi** [comment]
WE NEED MORE AXE

**Comment by iamyufi** [comment]
![image_2024-09-03_125354946](https://github.com/user-attachments/assets/91802ae4-61c7-423c-8866-6d46d86ad423)
